CREATE TABLE autor (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	nacionalidade VARCHAR(100) NOT NULL
);

CREATE TABLE livro (
	id SERIAL PRIMARY KEY,
	id_autor INTEGER REFERENCES autor(id) NOT NULL,
	titulo VARCHAR(100) NOT NULL,
	data_publicacao INTEGER NOT NULL
)